
import { Language, Job, SkillVideo, QuizQuestion } from './types';

export const APP_NAME = "Rozgar AI";

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', voiceCode: 'hi-IN' },
  { code: 'en', name: 'English', nativeName: 'English', voiceCode: 'en-IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', voiceCode: 'bn-IN' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', voiceCode: 'te-IN' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', voiceCode: 'ta-IN' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', voiceCode: 'mr-IN' },
];

export const JOB_CATEGORIES = [
  { id: 'driver', label: 'Driver', icon: 'Car' },
  { id: 'labour', label: 'Labour', icon: 'Hammer' },
  { id: 'maid', label: 'Maid', icon: 'Home' },
  { id: 'security', label: 'Security', icon: 'Shield' },
  { id: 'delivery', label: 'Delivery', icon: 'Bike' },
  { id: 'cook', label: 'Cook', icon: 'ChefHat' },
  { id: 'sales', label: 'Sales', icon: 'TrendingUp' },
];

export const SKILL_VIDEOS: SkillVideo[] = [
  { id: '1', title: 'Driving Etiquette & Safety', thumbnail: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=300', duration: '5 min', category: 'driver' },
  { id: '2', title: 'Basic English for Delivery', thumbnail: 'https://images.unsplash.com/photo-1616949338060-496677f4955b?auto=format&fit=crop&q=80&w=300', duration: '3 min', category: 'delivery' },
  { id: '3', title: 'Hygiene Tips for Cooks', thumbnail: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?auto=format&fit=crop&q=80&w=300', duration: '4 min', category: 'cook' },
  { id: '4', title: 'Interview Confidence', thumbnail: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=300', duration: '2 min', category: 'general' },
];

export const SKILL_QUIZ: QuizQuestion[] = [
  {
    id: '1',
    question: "You are late for a delivery. What should you do?",
    options: ["Drive very fast", "Call customer & inform", "Cancel the order"],
    correctAnswer: 1
  },
  {
    id: '2',
    question: "Customer is angry about cold food. You should:",
    options: ["Argue back", "Apologize politely", "Ignore them"],
    correctAnswer: 1
  },
  {
    id: '3',
    question: "What is most important for a driver?",
    options: ["Phone Battery", "Safety & Rules", "Loud Music"],
    correctAnswer: 1
  }
];

// Seed data
export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Car Driver',
    location: 'Andheri East, Mumbai',
    wage: 18000,
    wageType: 'monthly',
    description: 'Need a car driver for personal use. 10 hours duty.',
    employerId: 'emp1',
    employerName: 'Sharma Transports',
    employerVerified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    category: 'driver',
    urgent: true,
    distance: 2.5,
    status: 'OPEN',
    applicants: [],
    coordinates: { lat: 19.1136, lng: 72.8697 }
  },
  {
    id: '2',
    title: 'Construction Helper',
    location: 'Noida Sector 62',
    wage: 600,
    wageType: 'daily',
    description: 'Daily wage worker needed for construction site.',
    employerId: 'emp2',
    employerName: 'BuildWell Constructions',
    employerVerified: true,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    category: 'labour',
    urgent: false,
    distance: 5.0,
    status: 'OPEN',
    applicants: [],
    coordinates: { lat: 28.6280, lng: 77.3649 }
  },
  {
    id: '3',
    title: 'Security Guard',
    location: 'Koramangala, Bangalore',
    wage: 15000,
    wageType: 'monthly',
    description: 'Night shift security guard for apartment.',
    employerId: 'emp3',
    employerName: 'SafeGuard Agency',
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    category: 'security',
    urgent: true,
    distance: 1.2,
    status: 'OPEN',
    applicants: [],
    coordinates: { lat: 12.9352, lng: 77.6245 }
  },
  {
    id: '4',
    title: 'Delivery Boy',
    location: 'Laxmi Nagar, Delhi',
    wage: 20000,
    wageType: 'monthly',
    description: 'Food delivery partner needed. Bike required.',
    employerId: 'emp4',
    employerName: 'Zomato/Swiggy Partner',
    employerVerified: true,
    postedAt: new Date().toISOString(),
    category: 'delivery',
    urgent: true,
    distance: 3.8,
    status: 'OPEN',
    applicants: [
       { userId: 'worker_demo', userName: 'Raju Kumar', userPhone: '9876543210', status: 'PENDING', appliedAt: new Date().toISOString() }
    ],
    coordinates: { lat: 28.6304, lng: 77.2773 }
  },
  {
    id: '5',
    title: 'House Maid',
    location: 'Powai, Mumbai',
    wage: 8000,
    wageType: 'monthly',
    description: 'Cooking and cleaning for small family.',
    employerId: 'emp5',
    employerName: 'Mrs. Iyer',
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    category: 'maid',
    urgent: false,
    distance: 0.5,
    status: 'OPEN',
    applicants: [],
    coordinates: { lat: 19.1176, lng: 72.9060 }
  }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  hi: {
    find_job_btn: "नौकरी ढूंढें (बोलकर)",
    post_job_btn: "नौकरी पोस्ट करें",
    listening: "सुन रहा हूँ...",
    jobs_near_you: "आपके पास की नौकरियां",
    daily: "दैनिक",
    monthly: "मासिक",
    apply: "अप्लाई करें",
    applied: "अप्लाई किया",
    urgent: "ज़रूरी",
    employer_mode: "नौकरीदाता",
    worker_mode: "काम चाहिए",
    login_title: "लॉगिन करें",
    enter_phone: "मोबाइल नंबर डालें",
    get_otp: "OTP प्राप्त करें",
    welcome: "नमस्ते",
    dashboard: "डैशबोर्ड",
    profile: "प्रोफाइल",
    logout: "लॉग आउट",
    home_hero_title: "बोल के जॉब ढूंढो, 1 मिनट में",
    home_hero_subtitle: "भारत का सबसे सरल जॉब प्लेटफॉर्म",
    my_applications: "मेरी अर्जियां",
    search_jobs: "नौकरी खोजें",
    skills: "कौशल",
    experience: "अनुभव",
    save: "सेव करें",
    hired: "हायर किया",
    rejected: "अस्वीकार",
    pending: "पेंडिंग",
    seen: "देखा गया",
    interview: "इंटरव्यू",
    applicants: "उम्मीदवार",
    call_now: "कॉल करें",
    saved_jobs: "सेव की गई नौकरियां",
    learn: "सीखें",
    audio_resume: "आवाज़ में परिचय",
    download_resume: "रिज्यूमे डाउनलोड",
    map_view: "मैप देखें",
    list_view: "लिस्ट देखें",
    radius: "दूरी",
  },
  en: {
    find_job_btn: "Find Job (Voice)",
    post_job_btn: "Post a Job",
    listening: "Listening...",
    jobs_near_you: "Jobs Near You",
    daily: "Daily",
    monthly: "Monthly",
    apply: "Apply Now",
    applied: "Applied",
    urgent: "Urgent",
    employer_mode: "Employer",
    worker_mode: "Need Work",
    login_title: "Login",
    enter_phone: "Enter Mobile Number",
    get_otp: "Get OTP",
    welcome: "Namaste",
    dashboard: "Dashboard",
    profile: "Profile",
    logout: "Logout",
    home_hero_title: "Find a job by speaking, in 1 minute",
    home_hero_subtitle: "India's simplest job platform",
    my_applications: "My Applications",
    search_jobs: "Search Jobs",
    skills: "Skills",
    experience: "Experience",
    save: "Save",
    hired: "Hired",
    rejected: "Rejected",
    pending: "Pending",
    seen: "Seen",
    interview: "Interview",
    applicants: "Applicants",
    call_now: "Call Now",
    saved_jobs: "Saved Jobs",
    learn: "Upskill",
    audio_resume: "Voice Resume",
    download_resume: "Download CV",
    map_view: "Map View",
    list_view: "List View",
    radius: "Distance",
  },
  bn: {
    find_job_btn: "কাজ খুঁজুন (ভয়েস)",
    post_job_btn: "কাজ পোস্ট করুন",
    listening: "শুনছি...",
    jobs_near_you: "আপনার কাছাকাছি কাজ",
    daily: "দৈনিক",
    monthly: "মাসিক",
    apply: "আবেদন করুন",
    applied: "আবেদন করা হয়েছে",
    urgent: "জরুরী",
    employer_mode: "নিয়োগকর্তা",
    worker_mode: "কাজ চাই",
    login_title: "লগইন",
    enter_phone: "মোবাইল নম্বর লিখুন",
    get_otp: "OTP পান",
    welcome: "নমস্কার",
    dashboard: "ড্যাশবোর্ড",
    profile: "প্রোফাইল",
    logout: "লগ আউট",
    home_hero_title: "মুখে বলে কাজ খুঁজুন, ১ মিনিটে",
    home_hero_subtitle: "ভারতের সবচেয়ে সহজ জব প্ল্যাটফর্ম",
    my_applications: "আমার আবেদন",
    search_jobs: "কাজ অনুসন্ধান করুন",
    skills: "দক্ষতা",
    experience: "অভিজ্ঞতা",
    save: "সেভ করুন",
    hired: "নিয়োগ করা হয়েছে",
    rejected: "প্রত্যাখ্যাত",
    pending: "অপেক্ষমান",
    seen: "দেখা হয়েছে",
    interview: "ইন্টারভিউ",
    applicants: "আবেদনকারী",
    call_now: "কল করুন",
    saved_jobs: "সেভ করা কাজ",
    learn: "শিখুন",
    audio_resume: "ভয়েস রিজিউম",
    download_resume: "সিভি ডাউনলোড",
    map_view: "ম্যাপ ভিউ",
    list_view: "লিস্ট ভিউ",
    radius: "দূরত্ব",
  },
  te: {
    find_job_btn: "ఉద్యోగాన్ని వెతకండి",
    post_job_btn: "ఉద్యోగం పోస్ట్ చేయండి",
    listening: "వింటున్నాను...",
    jobs_near_you: "మీ దగ్గర ఉద్యోగాలు",
    daily: "రోజువారీ",
    monthly: "నెలవారీ",
    apply: "దరఖాస్తు చేయండి",
    applied: "దరఖాస్తు చేశారు",
    urgent: "అత్యవసరం",
    employer_mode: "యజమాని",
    worker_mode: "పని కావాలి",
    login_title: "లాగిన్",
    enter_phone: "మొబైల్ నంబర్",
    get_otp: "OTP పొందండి",
    welcome: "నమస్కారం",
    dashboard: "డాష్‌బోర్డ్",
    profile: "ప్రొఫైల్",
    logout: "లాగ్ అవుట్",
    home_hero_title: "మాట్లాడి ఉద్యోగం వెతకండి",
    home_hero_subtitle: "భారతదేశపు సరళమైన జాబ్ ప్లాట్‌ఫారమ్",
    my_applications: "నా దరఖాస్తులు",
    search_jobs: "ఉద్యోగాల శోధన",
    skills: "నైపుణ్యాలు",
    experience: "అనుభవం",
    save: "సేవ్ చేయండి",
    hired: "ఎంపికయ్యారు",
    rejected: "తిరస్కరించారు",
    pending: "పెండింగ్‌లో ఉంది",
    seen: "చూశారు",
    interview: "ఇంటర్వ్యూ",
    applicants: "అభ్యర్థులు",
    call_now: "కాల్ చేయండి",
    saved_jobs: "సేవ్ చేసిన ఉద్యోగాలు",
    learn: "నేర్చుకోండి",
    audio_resume: "వాయిస్ రెజ్యూమ్",
    download_resume: "CV డౌన్‌లోడ్",
    map_view: "మ్యాప్ వీక్షణ",
    list_view: "జాబితా వీక్షణ",
    radius: "దూరం",
  },
  ta: {
    find_job_btn: "வேலை தேடுங்கள்",
    post_job_btn: "வேலை இடுங்கள்",
    listening: "கேட்கிறது...",
    jobs_near_you: "அருகிலுள்ள வேலைகள்",
    daily: "தினசரி",
    monthly: "மாதாந்திர",
    apply: "விண்ணப்பிக்கவும்",
    applied: "விண்ணப்பித்தார்",
    urgent: "அவசரம்",
    employer_mode: "முதலாளி",
    worker_mode: "வேலை வேண்டும்",
    login_title: "உள்நுழைய",
    enter_phone: "மொபைல் எண்",
    get_otp: "OTP பெறவும்",
    welcome: "வணக்கம்",
    dashboard: "முகப்பு",
    profile: "சுயவிவரம்",
    logout: "வெளியேறு",
    home_hero_title: "பேசி வேலை தேடுங்கள், 1 நிமிடத்தில்",
    home_hero_subtitle: "இந்தியாவின் எளிய வேலை தளம்",
    my_applications: "விண்ணப்பங்கள்",
    search_jobs: "வேலை தேடல்",
    skills: "திறன்கள்",
    experience: "அனுபவம்",
    save: "சேமி",
    hired: "தேர்வு",
    rejected: "நிராகரிக்கப்பட்டது",
    pending: "நிலுவையில்",
    seen: "பார்க்கப்பட்டது",
    interview: "நேர்காணல்",
    applicants: "விண்ணப்பதாரர்கள்",
    call_now: "அழைக்கவும்",
    saved_jobs: "சேமித்த வேலைகள்",
    learn: "கற்க",
    audio_resume: "குரல் பயோடேட்டா",
    download_resume: "CV பதிவிறக்கம்",
    map_view: "வரைபடம்",
    list_view: "பட்டியல்",
    radius: "தூரம்",
  },
  mr: {
    find_job_btn: "नोकरी शोधा",
    post_job_btn: "नोकरी पोस्ट करा",
    listening: "ऐकत आहे...",
    jobs_near_you: "तुमच्या जवळच्या नोकऱ्या",
    daily: "दैनिक",
    monthly: "मासिक",
    apply: "अर्ज करा",
    applied: "अर्ज केला",
    urgent: "तातडीचे",
    employer_mode: "मालक",
    worker_mode: "काम पाहिजे",
    login_title: "लॉगिन",
    enter_phone: "मोबाईल नंबर",
    get_otp: "OTP मिळवा",
    welcome: "नमस्ते",
    dashboard: "डॅशबोर्ड",
    profile: "प्रोफाईल",
    logout: "लॉग आउट",
    home_hero_title: "बोलून नोकरी शोधा, १ मिनिटात",
    home_hero_subtitle: "भारताचे सर्वात सोपे जॉब प्लॅटफॉर्म",
    my_applications: "माझे अर्ज",
    search_jobs: "नोकरी शोधा",
    skills: "कौशल्य",
    experience: "अनुभव",
    save: "सेव्ह करा",
    hired: "निवड झाली",
    rejected: "नाकारले",
    pending: "प्रलंबित",
    seen: "पाहिले",
    interview: "मुलाखत",
    applicants: "उमेदवार",
    call_now: "कॉल करा",
    saved_jobs: "सेव्ह केलेल्या नोकऱ्या",
    learn: "शिका",
    audio_resume: "व्हॉइस रिझ्युमे",
    download_resume: "CV डाउनलोड",
    map_view: "नकाशा",
    list_view: "यादी",
    radius: "अंतर",
  }
};
